accounts/urls.py
from django.urls import path
from .views import HomeView,UserLoginView,UserLogoutView,notify,SignUpView,ActivateView,PasswordReset,PasswordResetDone,PasswordResetConfirm,PasswordResetComplete,MypageView,user_edit,UserDetailView

app_name='accounts'

urlpatterns=[
    path('home/',HomeView.as_view(),name='home'),
    path('login/',UserLoginView.as_view(),name='user_login'),
    path('logout/',UserLogoutView.as_view(),name='user_logout'),
    path('send_mail/',notify,name='send_mail'), #おためし
    path('signup/',SignUpView.as_view(),name='signup'),
    path('activate/<uidb64>/<token>',ActivateView.as_view(),name='activate'),
    path('password_reset/', PasswordReset.as_view(), name='password_reset'), 
    path('password_reset/done/', PasswordResetDone.as_view(), name='password_reset_done'), 
    path('reset/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('mypage/', MypageView.as_view(), name='mypage'),
    path('user_edit/', user_edit, name='user_edit'),
    path('user_detail/<int:pk>/',UserDetailView.as_view() , name='user_detail'),
]

boards/urls.py
from django.urls import path
from .views import TopView,ItemDetailView,item_create,MyItemsView,MyItemDeleteView,my_item_edit,ContactFormView,ContactResultView,toggle_favorite,favorite_list

app_name='boards'

urlpatterns=[
    path('top/',TopView.as_view(),name='top'),
    path('item_detail/<int:pk>/',ItemDetailView.as_view(),name='item_detail'),
    path('item_create/',item_create,name='item_create'),
    path('my_items/',MyItemsView.as_view(),name='my_items'),
    path('item_delete/<int:pk>/',MyItemDeleteView.as_view(),name='item_delete'),
    path('item_edit/<int:item_id>/',my_item_edit,name='item_edit'),
    path('item_contact/<int:item_id>/',ContactFormView.as_view(),name='item_contact'),
    path('item_contact_result/',ContactResultView.as_view(),name='item_contact_result'),
    path('toggle_favorite/<int:item_id>/',toggle_favorite,name='toggle_favorite'),
    path('favorite_list/',favorite_list,name='favorite_list'),
    #path('ajax_selected_city/',ajax_selected_city,name='ajax_selected_city'),
]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from boards import views

handler404=views.page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('boards/',include('boards.urls')),
]


if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

boards/models.py
from django.db import models
from accounts.models import User
from django.db.models import Q

#検索窓用モデル
class ItemsQuerySet(models.QuerySet):
    def search(self,query=None):
        qs = self #object.allとかそれらを含む
        if query is not None:
            or_lookup = ( #qオブジェクトを作成（なにで検索可能にするか）
                Q(name__icontains=query)|
                Q(comment__icontains=query)|
                Q(category__icontains=query)|
                Q(user__addresses__city__icontains=query)|
                Q(user__addresses__address__icontains=query)
            )
            qs=qs.filter(or_lookup).distinct()#重複を除く
        return qs.order_by("-created_at")
    
#検索窓用Itemsモデルマネージャー
class ItemsModelManager(models.Manager):
    def get_queryset(self):
        return ItemsQuerySet(self.model,using=self._db)
    
    def search(self,query=None):
        return self.get_queryset().search(query=query)

class Items(models.Model):
    CATEGORY_NAME=(
        ('家具','家具'),
        ('家電','家電'),
        ('自転車','自転車'),
        ('楽器','楽器'),
        ('生活雑貨','生活雑貨'),
        ('子供用品','子供用品'),
        ('ホビー、ゲーム','ホビー、ゲーム'),
        ('服/ファッション','服/ファッション'),
        ('靴/バック','靴/バック'),
        ('コスメ/ヘルスケア','コスメ/ヘルスケア'),
        ('食品','食品'),
        ('スポーツ','スポーツ'),
        ('その他','その他'),
    )
    item_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    comment = models.TextField(max_length=1000)
    favorited_by = models.ManyToManyField(User,related_name='favorite_items',blank=True)
    category = models.CharField(max_length=30,choices=CATEGORY_NAME)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 
    
    objects=ItemsModelManager()
    
    class Meta:
        verbose_name = '出品'
        verbose_name_plural = '出品一覧'
        
    def __str__(self):
        return self.name
    
class ItemPictures(models.Model):
    item_picture_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    item = models.ForeignKey(Items,on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='item_pictures/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = '出品写真'
        verbose_name_plural = '出品写真一覧'
        
    def __str__(self):
        return str(self.item.name)

#問い合わせフォーム用モデル
class Contact(models.Model):
    contact_id = models.AutoField(primary_key=True)
    item = models.ForeignKey(Items,on_delete=models.CASCADE)
    from_user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='from_user')
    to_user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='to_user')
    content = models.CharField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return 'from:'+self.from_user.email+' '+'to:'+self.to_user.email
    
    class Meta:
        verbose_name='お問い合わせ'
        verbose_name_plural='問い合わせ一覧'
        db_table='contacts'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">

      <!-- Bootstrap -->
      {% comment %} <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> {% endcomment %}

      <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.3.1/js/bootstrap.min.js"></script>

      <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
      <link href="{% static 'css/style.css' %}" rel="stylesheet">
      


      <!--MDBootstrapを導入-->
      <!-- Font Awesome -->
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
      <!-- Google Fonts -->
      <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
      <!-- MDB -->
      <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.css" rel="stylesheet"/>
      <!-- MDB -->
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.js"></script>

      <!-- 画像拡大用　-->
      <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>


   </head>
   <body>

      <nav class="navbar navbar-expand-sm navbar-light bg-light mb-5 fixed-top">
         <div class="container">
         
       
         <!-- メニュー項目 -->
         {% comment %} <div class="container collapse navbar-collapse" id="navbarNav"> {% endcomment %}
          
               <a class="navbar-brand" href="{% url 'boards:top' %}">
                 <img src="../../../media/tadadesu_pictures/icon.png" alt="アイコン">
               </a>

             <!-- ハンバーガーメニューボタン -->
            {% comment %} <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>  {% endcomment %}

            <div class="justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
            {% if user.is_authenticated %}
               <li class="nav-item">
                 <a class="nav-link" href="{% url 'accounts:mypage' %}">マイページ</a>
               </li>
               <li class="nav-item">
                 <a class="nav-link" href="{% url 'boards:item_create' %}">アイテムを出品する</a>
               </li>
               <li class="nav-item">
                 <a class="nav-link" href="{% url 'accounts:user_logout' %}">ログアウト</a>
               </li>
             {% else %}
               <li class="nav-item">
                 <a class="nav-link" href="{% url 'accounts:user_login' %}">ログイン</a>
               </li>
               <li class="nav-item">
                 <a class="nav-link" href="{% url 'accounts:signup' %}">新規登録</a>
               </li>
             {% endif %}
            </ul>
            </div>
         </div>
       </nav>
      {% block header %}
      {# top.htmlだけにヘッダー画像を表示#}
      {% endblock %}
      {% if messages %}
         {% for message in messages %}
         <p style=color:red>{{message.message}}</p>
         {% endfor %}
      {% endif %}
       
      
      <div class="container my-padding">
      {% block content %}
      
      {% block javascript %}
      <script>
         $(document).ready(function () {
           $('[data-toggle="collapse"]').click(function () {
             $('#navbarNav').toggleClass('show');
           });
         });
       </script>
      {% endblock %}
      {% endblock %}
      </div>
      

       
   </body>
{% block footer %}
<!-- Footer -->
<footer class="text-center text-lg-start bg-white text-muted">
   <!-- Section: Social media -->
   <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
     <!-- Left -->
     <div class="me-5 d-none d-lg-block">
       <span></span>
     </div>
     <!-- Left -->
 
     <!-- Right -->
     <div>
       <a href="" class="me-4 link-secondary">
         <i class="fab fa-facebook-f"></i>
       </a>
       <a href="" class="me-4 link-secondary">
         <i class="fab fa-twitter"></i>
       </a>
       <a href="" class="me-4 link-secondary">
         <i class="fab fa-google"></i>
       </a>
       <a href="" class="me-4 link-secondary">
         <i class="fab fa-instagram"></i>
       </a>
       <a href="" class="me-4 link-secondary">
         <i class="fab fa-linkedin"></i>
       </a>
       <a href="https://github.com/RyoKitamoto" class="me-4 link-secondary">
         <i class="fab fa-github"></i>
       </a>
     </div>
     <!-- Right -->
   </section>
   <!-- Section: Social media -->
 
   <!-- Section: Links  -->
   <section class="">
     <div class="container text-center text-md-start mt-5">
       <!-- Grid row -->
       <div class="row mt-3">
         <!-- Grid column -->
         <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
           <!-- Content -->
           <h6 class="text-uppercase fw-bold mb-4">
             <i class="fa-solid fa-seedling me-3 text-secondary"></i>タダデス
           </h6>
           <p>大阪府内のSDGsに貢献をめざす掲示板。あなたのいらないものは誰か必要としているかもしれない。その捨てようとしていたもの、あなたもぜひ出品してみませんか</p>
           
         </div>
         <!-- Grid column -->
 
         <!-- Grid column -->
         <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
           <!-- Links -->
           <h6 class="text-uppercase fw-bold mb-4">
             タダデスについて
           </h6>
           <p>
             <a href="#!" class="text-reset">会社概要</a>
           </p>
           <p>
             <a href="#!" class="text-reset">採用情報</a>
           </p>
           <p>
             <a href="#!" class="text-reset">公式ブログ</a>
           </p>
           <p>
             <a href="#!" class="text-reset">お知らせ/プレスリリース</a>
           </p>
         </div>
         <!-- Grid column -->
 
         <!-- Grid column -->
         <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
           <!-- Links -->
           <h6 class="text-uppercase fw-bold mb-4">
             ヘルプ
           </h6>
           <p>
             <a href="#!" class="text-reset">ヘルプセンター</a>
           </p>
           <p>
             <a href="#!" class="text-reset">よくあるQ&A</a>
           </p>
           
         </div>
         <!-- Grid column -->
 
         <!-- Grid column -->
         <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
           <!-- Links -->
           <h6 class="text-uppercase fw-bold mb-4">プライバシーと利用規約</h6>
           <p><a href="#!" class="text-reset">タダデス利用規約</a></p>
           <p>
            <a href="#!" class="text-reset">プライバシーポリシー</a>
           </p>
           <p><a href="#!" class="text-reset">プライバシーステートメント</a></p>
           <p><a href="#!" class="text-reset">健全化に資する運用方針</a></p>
           <p><a href="#!" class="text-reset">個人データの安全管理に係る基本方針</a></p>
         </div>
         <!-- Grid column -->
       </div>
       <!-- Grid row -->
     </div>
   </section>
   <!-- Section: Links  -->
 
   <!-- Copyright -->
   <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
     © 2023 Copyright: Tadadesu, Inc.
   </div>
   <!-- Copyright -->
 </footer>
 <!-- Footer -->
{% endblock %}
</html>

templates/filtered_items.html
{% for item in filtered_items %}
<p>{{item.user.addresses.city}}の出品</p>
<table style = border:solid;>
    <tr>
    <td>商品名</td>
    <td><a href="{% url 'boards:item_detail' item.item_id %}">{{item.name}}</a></td>
    </tr>
    <tr>
    <td>カテゴリー</td>
    <td>{{item.category}}</td>
    </tr>
    <tr>
    <td>地域</td>
    {% if item.user.addresses.city %}
    <td>{{item.user.addresses.city}}</td>
    {% else %}
    <td>未登録</td>
    {% endif %}
    </tr>
    <tr>
    <td>商品写真</td>
    <td>
    {% for picture in item.itempictures_set.all %}
    <img width=100px; height=100px; src="{{picture.picture.url}}">
    {% endfor %}
    </td>
    </tr>
    </table>
    <br>
{% empty %}
<p>出品がありません</p>
{% endfor %}

templates/item_delete.html
{% extends 'base.html'%}
{% block content%}
<br>
<h2>出品削除</h2>
<br><hr><br>
<p>本当にこの商品を削除しますか？<br>この操作は取り消しできません</p>
<form method='POST'>
    {% csrf_token %}
    <input type ="submit" value = "削除する" class="btn btn-success">
</form>
{% endblock %}

templates/item_detail.html
{% extends 'base.html'%}
{% block content%}


<h2>{{object.name}} 詳細ページ</h2>


<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
      <tr>
        <th>出品者</th>
        <th>カテゴリー</th>
        <th>市町村</th>
        <th>出品時間</th>
      
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <div class="d-flex align-items-center">
            <a href="{% url 'accounts:user_detail' object.user.user_id %}">
            <img
                src="{{object.user.picture.url}}"
                alt=""
                style="width: 100px; height: 100px"
                class="rounded-circle"
                />
            <div class="ms-3">
              <h5 class="fw-bold mb-1">{{object.user.username}}</h5>
              <p class="text-muted mb-0">
                {% if object.user.gender == 'man'%}
                性別：男性
                {% elif object.user.gender == 'woman'%}
                性別：女性
                {% else %}
                性別：無回答
                {% endif %}
              </p>
            </div>
            </a>
          </div>
        </td>
        <td>{{object.category}}</td>
        <td>
          {% if object.user.addresses%}
          <p class="fw-normal mb-1">大阪府</p>
          <p class="text-muted mb-0">{{object.user.addresses.city}}</p>
          {% else %}
          <p class="fw-normal mb-1">未登録</p>
          {% endif%}
        </td>
        <td>
          <p>{{object.created_at}}</p>
        </td>     
      </tr>
    </tbody>
</table>
<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
        <tr>
            <th>出品コメント</th>
            <th>現在のお気に入り数</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{object.comment}}</td>
            <td><p>{{favorite_count}}</p>
                {% if request.user in object.favorited_by.all %}
                <a href="{% url 'boards:toggle_favorite' object.item_id %}" class="btn btn-success">お気に入りから削除</a>
                {% else %}
                <a href="{% url 'boards:toggle_favorite' object.item_id %}" class="btn btn-success">お気に入りに追加</a>
                {% endif %}
            </td>
        </tr>
    </tbody>
</table>

<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
        <tr>
            <th>品物画像一覧(クリックすると拡大できます)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
        {% for picture in object.itempictures_set.all %}
        <td><a href="{{picture.picture.url}}" data-lightbox="group"><img width=200px; height=200px; src="{{picture.picture.url}}"></a></td>
        {% endfor %}
        </tr>
    </tbody>
</table>
<br>
<p><a href="{% url 'boards:item_contact' object.item_id %}" class="btn btn-success">この商品をお問い合わせする</a></p>



 


{% block javascript%}
<script>
$(document).ready(function(){
var lightbox = document.getElementById('lightbox');
var instance = new mdb.Lightbox(lightbox);
instance.open();
});
</script>

{% endblock%}
{% endblock %}

templates/my_items.html
{% extends 'base.html'%}
{% load paginate %}

{% block content%}
<br>
<h2>{{request.user.username}}さんが出品中のアイテム</h2>
<br><hr><br>
<div class="row">
    {% for object in object_list%}
    
      <div class="card col-4">
        <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light" style="height:200px">
          <img src="{{object.itempictures_set.first.picture.url}}" class="img-fluid" style="object-fit:cover"/>
          <a href="{% url 'boards:item_detail' object.item_id %}">
            <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
          </a>
        </div>
        <div class="card-body">
          <h4 class="card-title">{{object.name}}</h4>
          <p class="card-text">カテゴリー：{{object.category}}</p>
          <p class="card-text">
            市町村：
            {% if object.user.addresses.city %}
            {{object.user.addresses.city}}
            {% else %}
            未登録
            {% endif %}
          </p>
          <p class="card-text">
            <ul style="text-align:right; list-style:none;">
            <li><a href="{% url 'boards:item_edit' object.item_id %}">編集する</a></li>
            <li><a href="{% url 'boards:item_delete' object.item_id %}">削除する</a></li>
            </ul>
          </p>
        </div>
      </div>
    
      <br><br>
    {% endfor %}
    </div>
    <br>
    {# ページネーション #}
    <nav aria-label="Page navigation">
        <ul class="pagination text-center">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">前へ</span>
              </a>
            </li>
          {% endif %}
      
          {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
              <li class="page-item active"><a class="page-link" href="?{% url_replace request 'page' num %}">{{ num }}</a></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
              <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' num %}">{{ num }}</a></li>
            {% endif %}
          {% endfor %}
    
          
      
          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">次へ</span>
              </a>
            </li>
          {% endif %}
        </ul>
    </nav>
    

{% endblock %}

templates/mypage.html
{% extends 'base.html'%}
{% block content%}
<h2>{{user.username}}さんのマイページ</h2>
<br><hr><br>

<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
      <tr>
        <th>ニックネーム</th>
        <th>市町村</th>
        <th>登録日</th>
        <th>コメント</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <div class="d-flex align-items-center">
            <img
                src="{{user.picture.url}}"
                alt=""
                style="width: 250px; height: 250px"
                class="rounded-circle"
                />
            <div class="ms-3">
              <h5 class="fw-bold mb-1">{{user.username}}</h5>
              <p class="text-muted mb-0">
                {% if user.gender == 'man'%}
                性別：男性
                {% elif user.gender == 'woman'%}
                性別：女性
                {% else %}
                性別：無回答
                {% endif %}
              </p>
            </div>
          </div>
        </td>
        <td>
          {% if user.addresses%}
          <p class="fw-normal mb-1">大阪府</p>
          <p class="text-muted mb-0">{{user.addresses.city}}</p>
          {% else %}
          <p class="fw-normal mb-1">未登録</p>
          <p class="text-muted mb-0">住所を登録してサービスを開始しよう！</p>
          {% endif%}
        </td>
        <td>
          <p>{{user.created_at}}</p>
        </td>
        <td>{{user.comment}}</td>
        
      </tr>
    </tbody>
</table>


<p>{{user_address_edit_form.prefecture.errors}}</p>
<ul style="text-align:right; list-style:none;">
<li class="pb-3"><a href={% url 'accounts:user_edit' %}>マイページ情報更新</a></li>
<li class="pb-3"><a href={% url 'boards:my_items' %}>マイ投稿アイテム</a></li>
<li class="pb-3"><a href={% url 'boards:favorite_list' %}>お気に入りアイテム欄を見る</a></li>
</ul>
{% endblock %}

templates/password_reset_done.html
{% extends 'base.html'%}

{% block content %}
<br><br>
<form action="" method="POST">
<p>パスワードリセットのメールを送信しました。
<br/>
メールに記載されているリンクからパスワードの再設定を行ってください。
<br/>
<br/>
<br/>
<a class="btn btn-success col-4" href="{% url 'accounts:user_login' %}">ログイン画面へ</a>
</p>
</form>
{% endblock %}

templates/send_mail.html
{% extends 'base.html'%}
{% block content%}
<h2>コンソールにメールを送信しました</h2>

{% endblock %}

templates/top.html
{% extends 'base.html'%}
{% load paginate %}
{% block header %}
<header></header>
{% endblock%}
{% block content%}
{% if user.is_authenticated %}
<h2>ようこそタダデスへ！</h2>
<p>こんにちは!  {{request.user.username}}さん</p>
{% else %}
<h2>ようこそタダデスへ！</h2>
<p>こんにちは!  ゲストさん<br>新規登録完了で品物の投稿とお問い合わせができます</p>
{% endif %}
<br><hr><br>
<h3>現在の市町村ごとの出品状況</h3>
<ul style="display:flex; list-style:none; padding:0;">
{% for city_item_count in city_items_counts %}
    <li style="float:left;" class="m-1">{{city_item_count.city}}({{city_item_count.item_count}}件)</li>
{% endfor%}
</ul>



{#検索窓#}
<table>
    <tr>
<form method="get" action="">
    <td>{{ form.search }}</td>
    <td>{{ form.category }}</td>
    <td>
    <button class="btn btn-success" type="submit">検索</button>
    </td>
</form>
{#検索リセットボタン#}
<td>
<form method="get" action="{% url 'boards:top'%}">
    <button class="btn btn-success" type="submit">リセット</button>
</form>
</td>
</tr>
</table>
<br>
<hr>
<br>


<h5 class="mt-3"> {{ page_obj.paginator.count }}件の検索結果 </h5>

{# 品物カード #}
<div class="row">
{% for object in object_list%}

  <div class="card col-6">
    <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light" style="height:300px">
      <img src="{{object.itempictures_set.first.picture.url}}" class="img-fluid" style="object-fit:cover"/>
      <a href="{% url 'boards:item_detail' object.item_id %}">
        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
      </a>
    </div>
    <div class="card-body">
      <h4 class="card-title">{{object.name}}</h4>
      <p class="card-text">カテゴリー：{{object.category}}</p>
      <p class="card-text">
        市町村：
        {% if object.user.addresses.city %}
        {{object.user.addresses.city}}
        {% else %}
        未登録
        {% endif %}
      </p>
    </div>
  </div>

  <br><br>
{% endfor %}
</div>

<br>
{# ページネーション #}
<nav aria-label="Page navigation">
    <ul class="pagination text-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">前へ</span>
          </a>
        </li>
      {% endif %}
  
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <li class="page-item active"><a class="page-link" href="?{% url_replace request 'page' num %}">{{ num }}</a></li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' num %}">{{ num }}</a></li>
        {% endif %}
      {% endfor %}

      
  
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">次へ</span>
          </a>
        </li>
      {% endif %}
    </ul>
</nav>
{% block javascript %}

{% endblock%}
{% endblock %}

templates/user_login.html
{% extends 'base.html'%}
{% block content%}
<br>
<form method='POST'>
    {% csrf_token %}
    {{ form.non_field_errors }}
    <table>
    {% for field in form %}
        <tr>
        <td>{{ field.label }}</td>
        <td>{{ field }}</td>
        <td>{{ field.errors }}</td>
        </tr>
    {% endfor %}
    </table>
    <br>
    <input type="submit" value='ログイン'>
    </form>
    <br><hr><br>
    <p><a href="{% url 'accounts:password_reset'%}">パスワードを忘れた方はこちら</a></p>
{% endblock %}